// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Announcement struct {
	ID        pgtype.UUID
	Title     string
	Content   string
	Status    string
	Priority  int32
	Pinned    bool
	PublishAt pgtype.Timestamptz
	ExpireAt  pgtype.Timestamptz
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ApiKey struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	KeyPrefix        string
	KeyHash          string
	Name             string
	Status           string
	RpmLimit         int32
	ConcurrencyLimit int32
	ExpiresAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type AuditLog struct {
	ID             pgtype.UUID
	ActorID        pgtype.UUID
	Action         string
	TargetType     string
	TargetID       pgtype.UUID
	BeforeSnapshot []byte
	AfterSnapshot  []byte
	Ip             *netip.Addr
	UserAgent      pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type BalanceLedger struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Type           string
	Amount         pgtype.Numeric
	BalanceBefore  pgtype.Numeric
	BalanceAfter   pgtype.Numeric
	BaseCost       pgtype.Numeric
	RateMultiplier pgtype.Numeric
	RelatedType    pgtype.Text
	RelatedID      pgtype.UUID
	OperatorID     pgtype.UUID
	Remark         string
	CreatedAt      pgtype.Timestamptz
}

type ChannelModel struct {
	ID                pgtype.UUID
	ChannelID         pgtype.UUID
	ModelID           pgtype.UUID
	UpstreamModelName string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type GatewayRequest struct {
	ID               pgtype.UUID
	RequestID        string
	UserID           pgtype.UUID
	ApiKeyID         pgtype.UUID
	ModelID          pgtype.UUID
	ChannelID        pgtype.UUID
	Endpoint         string
	Status           string
	HttpStatus       int32
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	BaseCost         pgtype.Numeric
	RateMultiplier   pgtype.Numeric
	Charge           pgtype.Numeric
	IsStream         bool
	IsEstimated      bool
	LatencyMs        int32
	ErrorCode        pgtype.Text
	ErrorMessage     pgtype.Text
	ClientIp         *netip.Addr
	CreatedAt        pgtype.Timestamptz
}

type Model struct {
	ID               pgtype.UUID
	PublicName       string
	Type             string
	ModelGroup       string
	BillingMode      string
	InputPricePer1k  pgtype.Numeric
	OutputPricePer1k pgtype.Numeric
	PricePerCall     pgtype.Numeric
	RateMultiplier   pgtype.Numeric
	Status           string
	SortOrder        int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type RedeemCode struct {
	ID         pgtype.UUID
	CodeHash   string
	CodePrefix string
	BatchName  string
	Amount     pgtype.Numeric
	Status     string
	MaxUses    int32
	UsedCount  int32
	ExpiresAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type RedeemRecord struct {
	ID           pgtype.UUID
	RedeemCodeID pgtype.UUID
	UserID       pgtype.UUID
	Amount       pgtype.Numeric
	LedgerID     pgtype.UUID
	ClientIp     *netip.Addr
	CreatedAt    pgtype.Timestamptz
}

type SystemSetting struct {
	Key         string
	Value       string
	Description string
	UpdatedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
}

type UpstreamChannel struct {
	ID               pgtype.UUID
	Name             string
	ProviderType     string
	BaseUrl          string
	ApiKeyEncrypted  string
	Status           string
	Weight           int32
	TimeoutSeconds   int32
	RpmLimit         int32
	ConcurrencyLimit int32
	FailThreshold    int32
	FailCount        int32
	Health           string
	LastSuccessAt    pgtype.Timestamptz
	LastErrorAt      pgtype.Timestamptz
	LastErrorMessage pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Username     string
	Email        pgtype.Text
	PasswordHash string
	Role         string
	Status       string
	Balance      pgtype.Numeric
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
}
